FROM oven/bun:1

ARG DB_URL

WORKDIR /usr/src/app

COPY . .

RUN bun install

RUN bun run db:generate
RUN bun run build:web

RUN DB_URL=$DB_URL bunx turbo build --filter=web...

EXPOSE 3000

# Start the frontend application
CMD ["bun", "start:web"]