FROM oven/bun:1

ARG DB_URL

WORKDIR /usr/src/app

COPY ./packages ./packages 
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY apps/web/package.json ./apps/web/package.json

COPY . .

RUN bun install
RUN bun run db:generate
# RUN DB_URL=${DB_URL} bun run build:web
RUN DB_URL=${DB_URL} bunx turbo build --filter=web...

EXPOSE 3000

# Start the frontend application
CMD ["bun", "run", "start:web"]

